//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseRegistration
    {
        public int id { get; set; }
        public int Trainerid { get; set; }
        public int courseid { get; set; }
        public System.DateTime createdDate { get; set; }
        public bool isDone { get; set; }
        public int TotalPoint { get; set; }
        public byte[] Certificateid { get; set; }
        public string comment { get; set; }
    
        public virtual course course { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
